version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yashwanthnaidu
      POSTGRES_DB: pixelspeak
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"